import type { MobxQuery } from "@tinkerbells88/mobx-query";
import { mountReactMobxQueryDevtools } from "./react";

export type MobxQueryDevtoolsOptions = {
  /** Start with the panel visible. Defaults to false. */
  initialIsOpen?: boolean;
  /** Placement of the launcher. Defaults to bottom-right. */
  position?: "bottom-left" | "bottom-right";
};

const styles = `
  :host { all: initial; }
  *, *::before, *::after { box-sizing: border-box; }
  .mq-root { --bg:#1d1512; --panel:#261b17; --line:#533a2f; --text:#fff5ed; --muted:#c7aaa0; --orange:#ff9955; --orange-hot:#ff6d3d; --blue:#4da3ff; --green:#7ee2b8; --red:#ff8e78; --yellow:#ffd166; color:var(--text); font-family:ui-sans-serif,system-ui,sans-serif; }
  button, input, textarea { font:inherit; } button { cursor:pointer; color:inherit; }
  .launcher { position:fixed; z-index:2147483646; bottom:18px; width:46px; height:46px; display:grid; place-items:center; border:1px solid #ffb178; border-radius:14px; background:linear-gradient(145deg,var(--orange-hot),#d9462f); box-shadow:0 12px 34px rgba(81,24,13,.45); transition:transform 150ms cubic-bezier(.2,.8,.2,1),filter 150ms ease; } .launcher.right { right:18px; } .launcher.left { left:18px; } .launcher:hover { transform:translateY(-2px); filter:brightness(1.08); } .launcher:active,.action:active,.icon-button:active { transform:scale(.97); } .launcher svg { width:24px; fill:none; stroke:#fff7ed; stroke-width:1.8; }
  .count { position:absolute; top:-6px; right:-6px; min-width:19px; height:19px; padding:0 5px; border:2px solid var(--bg); border-radius:99px; background:var(--blue); color:#fff; font:700 11px/15px ui-monospace,monospace; text-align:center; }
  .panel { position:fixed; z-index:2147483645; bottom:76px; width:min(900px,calc(100vw - 32px)); height:min(570px,calc(100vh - 100px)); display:grid; grid-template-rows:auto auto 1fr; overflow:hidden; border:1px solid #714a37; border-radius:16px; background:var(--bg); box-shadow:0 24px 70px rgba(42,16,8,.58); animation:mq-in 180ms cubic-bezier(.2,.8,.2,1); } .panel.right { right:16px; transform-origin:bottom right; } .panel.left { left:16px; transform-origin:bottom left; } @keyframes mq-in { from { opacity:0; transform:translateY(8px) scale(.98); } to { opacity:1; transform:none; } }
  .topbar,.controls { display:flex; align-items:center; gap:10px; border-bottom:1px solid var(--line); } .topbar { min-height:52px; padding:0 14px 0 17px; background:linear-gradient(110deg,#382019,#211512); } .controls { padding:10px 12px; background:#211714; } .brand { display:flex; align-items:center; gap:9px; color:#fff8ef; font:700 14px/1 ui-monospace,monospace; } .brand-mark { width:20px; height:20px; border:2px solid #ffcfaa; border-radius:50% 45% 50% 42%; background:radial-gradient(circle at 32% 28%,#ffd58b 0 16%,transparent 18%),linear-gradient(135deg,var(--orange-hot),#c83429); box-shadow:inset -3px -3px 0 rgba(115,26,13,.3); } .summary { display:flex; gap:7px; margin-left:auto; }
  .pill { display:inline-flex; align-items:center; gap:5px; padding:4px 7px; border-radius:6px; background:rgba(255,153,85,.1); color:var(--muted); font:600 11px/1 ui-monospace,monospace; } .pill b { color:#fff2e5; } .icon-button { width:29px; height:29px; border:0; border-radius:7px; background:transparent; color:var(--muted); font-size:20px; } .icon-button:hover { background:rgba(255,153,85,.12); color:#fff2e5; } .search { width:100%; max-width:350px; padding:8px 10px; border:1px solid #684535; border-radius:8px; outline:none; background:#17100e; color:var(--text); font-size:12px; } .search:focus,.code:focus { border-color:var(--orange); box-shadow:0 0 0 3px rgba(255,153,85,.14); }
  .workspace { min-height:0; display:grid; grid-template-columns:305px minmax(0,1fr); } .sidebar { overflow:auto; border-right:1px solid var(--line); background:#211714; } .group-title,.section-title { margin:0; padding:13px 14px 7px; color:#d39b7e; font:600 10px/1 ui-monospace,monospace; letter-spacing:.08em; text-transform:uppercase; } .entry { width:100%; display:flex; gap:10px; padding:10px 13px; border:0; border-left:2px solid transparent; background:transparent; text-align:left; } .entry:hover { background:rgba(255,153,85,.07); } .entry.selected { border-left-color:var(--orange); background:linear-gradient(90deg,rgba(255,109,61,.18),rgba(255,153,85,.05)); } .entry-content { min-width:0; flex:1; } .entry-key,.entry-meta { display:block; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; font-family:ui-monospace,monospace; } .entry-key { color:#fff0e4; font-size:12px; } .entry-meta { margin-top:4px; color:#ad8878; font-size:11px; } .dot { flex:none; width:8px; height:8px; margin-top:4px; border-radius:99px; background:#9b786b; } .dot.loading { background:var(--yellow); } .dot.error { background:var(--red); } .dot.success { background:var(--green); }
  .inspector { min-width:0; overflow:auto; padding:18px; background:radial-gradient(circle at 90% 0,rgba(255,109,61,.08),transparent 28%); } .inspector-empty { display:grid; height:100%; place-content:center; color:var(--muted); text-align:center; font-size:13px; } .detail-head { display:flex; gap:12px; margin-bottom:16px; } .detail-title { min-width:0; flex:1; } .detail-key { margin:0; overflow-wrap:anywhere; font:600 14px/1.45 ui-monospace,monospace; } .detail-sub { margin:5px 0; color:var(--muted); font:11px/1.3 ui-monospace,monospace; } .status-label { padding:5px 8px; border-radius:6px; font:700 10px/1 ui-monospace,monospace; text-transform:uppercase; } .status-label.loading { background:var(--yellow); color:#663d0b; } .status-label.success { background:var(--green); color:#174d37; } .status-label.error { background:var(--red); color:#6b1d14; } .status-label.idle { background:#584039; }
  .actions { display:flex; flex-wrap:wrap; gap:7px; margin:0 0 16px; } .action { padding:7px 9px; border:1px solid #704a38; border-radius:7px; background:#34231d; color:#ffe7d5; font-size:11px; transition:transform 150ms cubic-bezier(.2,.8,.2,1),background 150ms ease,border-color 150ms ease; } .action:hover { border-color:var(--orange); background:#4a2d22; } .action:disabled { cursor:not-allowed; opacity:.45; } .meta-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:7px; } .meta { padding:8px 9px; border:1px solid #53382c; border-radius:7px; background:#251915; } .meta span { display:block; color:#b7846e; font:10px/1 ui-monospace,monospace; text-transform:uppercase; } .meta b { display:block; margin-top:4px; color:#ffe6d4; font:600 11px/1.25 ui-monospace,monospace; } .section-title { padding:15px 0 7px; } .code,.error-box { width:100%; margin:0; padding:10px; border:1px solid #583a2c; border-radius:8px; background:#160f0d; color:#f9d7c1; font:11px/1.55 ui-monospace,monospace; white-space:pre-wrap; } .code { min-height:88px; resize:vertical; outline:none; } .readonly { resize:none; } .error-box { border-color:rgba(255,142,120,.42); background:rgba(112,31,19,.24); color:#ffd1c7; } .empty-list { padding:34px 20px; color:var(--muted); text-align:center; font-size:13px; }
  @media (max-width:650px) { .panel { height:min(650px,calc(100vh - 90px)); bottom:70px; } .workspace { grid-template-columns:1fr; grid-template-rows:190px minmax(0,1fr); } .sidebar { border-right:0; border-bottom:1px solid var(--line); } .summary .pill:not(:first-child) { display:none; } .meta-grid { grid-template-columns:1fr; } }
`;

export function mountMobxQueryDevtools(
  client: MobxQuery,
  target: HTMLElement = document.body,
  options: MobxQueryDevtoolsOptions = {},
) {
  return mountReactMobxQueryDevtools(client, target, options, styles);
}
